### ISSUE TITLE
Hard to click with Fat fingers on Radio button.

### ISSUE THREAD

**Issue by sonikatrip** [esims-io/esims-io-issues#2]
Forget the fact that I selected the text, but I have to click right on the radio icon, the whole link "Most data" needs to be clickable, really hard to just click the radio button with fat fingers.

![IMAGE 2021-11-25 21:51:28](https://user-images.githubusercontent.com/4548507/143502646-b22b70ef-2764-4839-ae1a-f0945ce02f95.jpg)

**Comment by anes-djebbar** [comment]
https://github.com/esims-io/esims-web-v2/pull/81
